# Site settings
title: Liberty Power Gardens
description: >-
  Community-scale food waste recycling that diverts waste from landfills,
  reduces greenhouse gas emissions, and returns renewable energy and resources
  to the neighborhoods we serve.
baseurl: "/"
url: "https://libertypowergardens.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed
